Repository isaacmsl/ezcommerce, pull requests merged in 2021-03, with the labels that each got.

#49 Tela cadastro produto
  cadastroProduto.php
  public/archive.svg
  public/box.svg
  public/dollar.svg
  public/image.svg
  public/scripts/limitarInputNumero.js
  public/scripts/uploadImgProduto.js
  styles/form/form.css
Labels: enhancement, frontend

#53 (front) Tela inicial
  index.php
  public/cart.svg
  public/heart-filled.svg
  public/heart.svg
  public/help.svg
  public/home.svg
  public/log-in.svg
  public/log-out.svg
  public/logo-ez-dark.svg
  public/pizza-napolitana.jpg
  public/plus.svg
  public/search.svg
  styles/btns/cta.css
  styles/cards/produto/produto.css
  styles/global.css
  styles/nav/nav.css
  styles/pages/inicial.css
Labels: enhancement, frontend

#55 Manter produto
  .github/workflows/tdd.yml
  composer.json
  composer.lock
  src/data/banco.db
  src/data/bancoTeste.db
  src/data/produto/createTable.php
  src/data/produto/insertInto.php
  src/data/sqlite/SQLiteConnection.php
  src/models/Produto.php
  src/models/persistencia/ProdutoDAO.php
  src/utils/ImgBB.php
  tests/ImgBBTest.php
  tests/ProdutoTest.php
Labels: backend, enhancement

#56 Produto controller
  src/actions/produto.php
  src/controllers/ProdutoController.php
  src/data/banco.db
  src/data/bancoTeste.db
  tests/ImgBBTest.php
Labels: backend, enhancement

#61 (back) Fix models sem dao
  src/controllers/LoginController.php
  src/controllers/ProdutoController.php
  src/controllers/UsuarioController.php
  src/models/Produto.php
  src/models/Usuario.php
Labels: backend, bug

#62 Front editar perfil com back
  editarPerfil.php
  index.php
  src/controllers/LoginController.php
  src/controllers/UsuarioController.php
  src/utils/getUsuarioUnserialize.php
  styles/span/span.css
Labels: enhancement, frontend

#64 Front listar produtos
  cadastroPerfil.php
  index.php
  src/controllers/ProdutoController.php
  src/controllers/UsuarioController.php
Labels: enhancement, frontend

#63 Front cadastro produtos com back
  cadastroProduto.php
  index.php
Labels: enhancement, frontend

#67 Fix listar todos produtos
  index.php
  src/controllers/ProdutoController.php
  src/models/Produto.php
  src/models/persistencia/ProdutoDAO.php
  tests/ProdutoTest.php
Labels: backend, enhancement, frontend

#69 ++icones quando o produto é do user logado
  index.php
  public/edit.svg
  public/trash.svg
  styles/cards/produto/produto.css
Labels: enhancement, frontend

#68 Curtir produto
  index.php
  src/actions/curtir.php
  src/models/persistencia/ProdutoDAO.php
  styles/cards/produto/produto.css
Labels: enhancement, frontend

#70 Front editar/remover produtos com back
  editarProduto.php
  index.php
  src/controllers/ProdutoController.php
  styles/cards/produto/produto.css
Labels: enhancement, frontend

#71 ++fix numero input tela cadastro perfil
  public/scripts/limitarInputNumero.js
Labels: bug, frontend

#72 Front remover perfil com back
  editarPerfil.php
  index.php
  public/scripts/editarPerfil.js
  src/controllers/UsuarioController.php
  styles/btns/ghost.css
Labels: enhancement, frontend

#73 Fix alterar listar
  editarProduto.php
  src/actions/curtir.php
  src/controllers/ProdutoController.php
  src/models/persistencia/ProdutoDAO.php
Labels: backend, frontend

#74 ++listar produto por email de usuario
  src/controllers/ProdutoController.php
  src/models/persistencia/ProdutoDAO.php
Labels: backend, enhancement

#75 Front resolvendo alguns bugs
  index.php
  styles/cards/produto/produto.css
  styles/form/form.css
  styles/global.css
  styles/pages/inicial.css
Labels: enhancement, frontend

#80 Popup remocoes
  editarPerfil.php
  editarProduto.php
  index.php
  public/scripts/popupConfirmar.js
  public/scripts/popupConfirmarForm.js
  styles/cards/produto/produto.css
Labels: enhancement, frontend

#83 ++front mostrando aviso ao errar o login
  login.php
  src/controllers/LoginController.php
Labels: enhancement, frontend

#84 removidas linhas denecessarias de DAO
  src/models/persistencia/ProdutoDAO.php
Labels: bug

#86 ++usuarios e produtos no banco.db
  src/data/banco.db
Labels: backend

#87 ++btn cadastro perfil tela inicial
  index.php
  styles/pages/inicial.css
Labels: enhancement, frontend

#88 Front qnt estoque
  cadastroProduto.php
  editarProduto.php
  index.php
  public/scripts/limitarInputNumero.js
  styles/cards/produto/produto.css
Labels: enhancement, frontend

#89 Front filtrar produto por nome
  index.php
  public/scripts/buscarProduto.js
  styles/cards/produto/produto.css
Labels: backend, enhancement

#90 Front carrinho
  carrinho.php
  index.php
  public/cart-green.svg
  public/scripts/precosCarrinho.js
  public/x.svg
  styles/btns/ghost.css
  styles/cards/produto/produto.css
  styles/global.css
  styles/pages/carrinho.css
  styles/tables/carrinho.css
Labels: enhancement, frontend

#91 Back carrinho
  carrinho.php
  index.php
  src/actions/carrinho.php
  src/actions/logout.php
  src/utils/getCarrinhoUnserialize.php
Labels: enhancement, frontend
